config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'pages#home'
  resources :costumes do
    resources :bookings, only: %i[new create]
  end
  resource :dashboard, only: [:show]
  resources :bookings, only: %i[update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :costume

  enum status: [ :pending, :accepted, :declined ]
  before_create :set_total_price

  def set_total_price
    self.total_price = (self.end_date - self.start_date).to_i * costume.price
  end
end

app/models/costume.rb
class Costume < ApplicationRecord
  SIZES = ["XS", "S", "M", "L", "XL", "XXL"]
  CATEGORIES = ["Male", "Female", "Child", "Pets"]
  COLORS = ["Black", "White", "Red", "Blue", "Yellow"]
  OCCASIONS = ["Party", "Birthday", "Halloween", "Carnival", "Christmas", "Animals"]
  CONDITIONS = ["Very Used", "Gently used", "Good condition", "Very good condition", "Perfect condition"]

  belongs_to :user
  has_many :bookings, dependent: :destroy
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :costumes
  has_many :recieved_bookings, through: :costumes, source: :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @costume = Costume.find(params[:costume_id])
    @booking = Booking.new
  end

  def create
    @costume = Costume.find(params[:costume_id])
    @booking = Booking.new(booking_params)
    @booking.costume = @costume
    @booking.user = current_user

    if @booking.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])

    if params[:status] == "accepted"
      # @booking.update(status: "accepted")
      @booking.accepted!
      redirect_to dashboard_path, notice: "Successfully accepted"
    elsif params[:status] == "declined"
      # @boooking.update(status: "declined")
      @booking.declined!
      redirect_to dashboard_path, notice: "Successfully decline"
    end

  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :user_id, :costume_id, :status, :message)
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  def index
    if params[:occasion]
      @costumes = Costume.geocoded.where(occasion: params[:occasion])
    elsif params[:category]
      @costumes = Costume.geocoded.where(category: params[:category])
    elsif params[:query]
      @costumes = Costume.geocoded.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @costumes = Costume.all
    end
    @markers = @costumes.geocoded.map do |costume|
      {
        lat: costume.latitude,
        lng: costume.longitude,
        info_window: render_to_string(partial: "info_window", locals: { costume: costume }),
        image_url: helpers.asset_url("pin.png") # Here you can change the mark
      }
    end
  end

  def show
    @costume = Costume.find(params[:id])
  end

  def new
    @costume = Costume.new
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.user = current_user
    if @costume.save!
      redirect_to costume_path(@costume)
    else
      render :new
    end
  end

  def search


  end

  private

  def costume_params
    params.require(:costume).permit(:name, :description, :size, :location, :category, :color, :price, :user_id, :occasion, :condition, :photo)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @recieved_bookings = current_user.recieved_bookings
    @bookings = current_user.bookings
    @costumes = current_user.costumes
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="new-booking-container">
  <div class="form-group d-flex mx-auto">
    <%= simple_form_for [@costume, @booking] do |f| %>
    <div class="form-container">

      <div class="page-one-booking align" style="display: flex">
        <div>
            <h1 class="text-justify"><strong><span>Amazing costume find!</span></strong><h1>
            <h3>Let's go through these next <em><span><strong>super</strong></span></em> simple steps to send a booking request!</h3>
          </div>
      </div>

      <div class="page-two-booking align" style="display: none">
        <div>
          <h1><strong>Step 1:</strong> For how long would you like to rent the costume?</h1><br>
          <div class="d-flex">
            <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"}%>
             <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          </div>
        </div>
      </div>

      <div class="page-three-booking align" style="display: none">
        <div>
          <h1><strong>Step 2:</strong> Any additional final words you would like to add to your request?</h1>
          <%= f.input :message, label: "Your sweet message:" %><br>
        </div>
      </div>

      <div class="page-four-booking align" style="display: none">
        <div>
          <h1><strong>Step 3:</strong> Push the button to submit the request!</h1>
          <%= f.submit "Send costume request!", class: "btn btn-form-submit" %><br>
        </div>
      </div>

    </div>
    <% end %>
    <button class="next-step-booking btn-styling">next step</button>

  </div>
</div>

app/views/costumes/_info_window.html.erb
<h2><%=costume.name %></h2>
<p class="fas fa-map-marker-alt"><%=costume.location %></p>
<img src="<%=url_for(costume.photo)%>" width="200px" height="200px">
<!--^here we will change width and height and customize it better-->

app/views/costumes/index.html.erb
<div class="costumes_index">
  <div class="left">
    <% if params[:occasion] %>
      <h1><%= params[:occasion].capitalize %> costumes</h1>
    <% elsif params[:category] %>
       <h1><%= params[:category].capitalize %>'s costumes</h1>
    <% else %>
         <h1><%= params[:query] %></h1>
    <% end %>

    <div>
      <%= form_tag costumes_path, method: :get, class: "form-inline" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control searchbar-design-index",
        placeholder: "Find a costume"
      %>
      <%= submit_tag "Search", class: "btn btn-flat-search-index" %>
    </div>
    <% end %>

    <div class="buttons">
      <a href="#" class="filter-button">Category</a>
      <a href="#" class="filter-button">Occasion</a>
      <a href="#" class="filter-button">Condition</a>
    </div>

  <div class="cards">
    <% @costumes.each do |costume| %>
      <%= link_to costume_path(costume) do %>
        <div class="card">
          <% if costume.photo.attached? %>
            <%= cl_image_tag costume.photo.key, class: "card-img"%>
          <% end %>
          <div class="card-text">
            <%= costume.name.capitalize %>
            <p class="pricelocation"><%= costume.price%>€/per day</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  </div>

  <div class="right">
    <div id="map"
     style="width: 100%; height: 100vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>
  </div>

</div>

<div></div>

app/views/costumes/new.html.erb
  <div class="new-costume-container">
    <div class="new-costume-pt-one">
      <div class="new-costume-img" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.3)), url(https://inst-2.cdn.shockers.de/hs_cdn/out/pictures/master/product/1/queen-elisabeth-maennerkostuem-queen-elisabeth-male-costume-drag-queen-kostuem-36845-01.jpg)">
        <ul>
          <li><h1><strong>Prepare your costume!</strong></h1></li>
          <li><p>Let's upload it to <em class="mark-text"> <span class="green-font">Costume Rack</span></em></p></li>
        </ul>
      </div>
    </div>
    <div class="new-costume-pt-two">
      <div class="form-group">
        <%= simple_form_for @costume do |f| %>
          <div class="container form-container">
            <div class="step-one text-center fix" style="display: block">
              <h1 class="form-instruction"><strong>Step 1:</strong> Upload your costume picture!</h1>
                <%= f.input :photo, as: :file, label: "Attachment:" %><br>
            </div>

            <div class="step-two text-center fix" style="display: none">
              <h1 class="form-instruction"><strong>Step 2:</strong> Add costume name & description</h1>
              <div class="col-12 form-group line">
                <%= f.input :name, label: "Costume name:" %><br>
              </div>
              <div class="col-12 form-group line">
                <%= f.input :description, label: "Costume description:" %><br>
              </div>
            </div>

            <div class="step-three text-center" style="display: none">
              <h1 class="form-instruction"><strong>Step 3:</strong> What's the occasion?<br>  ...and for whom?</h1>
              <div class="col-12 form-group line">
                <%= f.input :occasion, collection: Costume::OCCASIONS, label: "Costume occasion:" %>
              </div>
              <div class="col-12 form-group line">
                <%= f.input :category, collection: Costume::CATEGORIES, label: "Costume category:" %>
              </div>
              <div class="col-12 form-group line">
                <%= f.input :condition, collection: Costume::CONDITIONS, label: "Costume condition:" %><br>
              </div>
            </div>

            <div class="step-four text-center fix" style="display: none">
              <h1 class="form-instruction"><strong>Step 4:</strong> Please specify last couple of details. And the $ of course! </h1>
              <div class="form-row col-10 mx-auto">
                <div class="col-6 form-group line mx-auto">
                  <%= f.input :size, collection: Costume::SIZES, label: "Costume size:" %>
                </div>
                <div class="col-6 form-group line">
                  <%= f.input :color, collection: Costume::COLORS, label: "Costume color:"%>
                </div>
              </div>
              <div class="form-group col-10 mx-auto line">
                <%= f.input :location, label: "Costume pick-up location:" %>
              </div>
              <div class="form-group col-10 mx-auto line">
                <%= f.input :price, label: "Costume price:" %><br>
              </div>
              <%= f.submit "Create new costume", class: "btn btn-form-submit" %><br>
            </div>
          </div>
        <% end %>
      </div>

      <button class="next-step btn-styling">Next Step</button>
    </div>
  </div>

app/views/costumes/show.html.erb
<div class="container">
  <div class="center-section">
    <%= cl_image_tag @costume.photo.key, class: "costume-img" %>
    <div class="costume-card-infos list-inline">
      <div class="owner">
        <div class="costume-name mr-5">
        <h1><%= @costume.name.capitalize %></h1>
        </div>
        <p class="owner" style = ""><%= @costume.user.first_name %></p>
        <%= image_tag "https://i5.walmartimages.com/asr/768c1077-d262-40bc-872d-cfd3ae86b33f_1.0cac95463c1774eef3e93d818ce3320e.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", class: "avatar dropdown-toggle avatar-square"%>
      </div>
      <div class="icons">
        <ul class="list-inline">
          <li><i class="fas fa-star"></i></li>
          <li><i class="fas fa-star"></i></li>
          <li><i class="fas fa-star"></i></li>
          <li><i class="far fa-star"></i></li>
          <li><i class="far fa-star"></i></li>
        </ul>
      </div>
      <div class="features">
        <p><%= @costume.description %></p>
        <ul class="costume-details mt-3">
          <li><%= image_tag "man.png", class: "costume-icons" %>  <%= @costume.category.capitalize %></li>
          <li><%= image_tag "party-popper.png", class: "costume-icons" %>  <%= @costume.occasion.capitalize %></li>
          <li><%= image_tag "size-guide.png", class: "costume-icons" %>  <%= @costume.size.capitalize %></li>

        </ul>
        <ul class="costume-details mt-3">

          <li><%= image_tag "colorchoice.png", class: "costume-icons" %>  <%= @costume.color.capitalize %></li>
          <li><%= image_tag "condition.png", class: "costume-icons" %>  <%= @costume.condition.capitalize %></li>
        </ul>
      </div>
      <div class="price">
        <p>€<%= @costume.price %></p>
      </div>
      <div class="header justify-content-end">
        <%= link_to new_costume_booking_path(@costume) do %>
          <button type="button" class="button-availability">Book this costume!</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="container">
  <div class="user-info d-flex align-items-center">
    <h1> Welcome to your dashboard <%= current_user.first_name %>!</h1>
    <%= image_tag "woman.png", class: "avatar" %>
  </div>
  <div class="user-data">
      <p>My costumes: <strong><%= @costumes.count %></strong></p>
      <p>My requests: <strong><%= @recieved_bookings.count %></strong></p>
      <p>My pending requests: <strong><%= @bookings.count %></strong></p>
    </div>
  <div class="bookings-division">
    <div class="sent-bookings border-right">
      <h4>Sent requests</h4>
      <div class="dash-cards">
        <% @bookings.each do | booking | %>
        <div class="dash-card">
          <%= cl_image_tag booking.costume.photo.key %>
          <div class="dash-card-infos">
            <h6><strong><%= booking.costume.name.capitalize %></strong></h6>
            <p><%= booking.costume.description.capitalize %></p>
            <p>Status: <%= booking.status%></p>
            <p>Total price: <strong><%= booking.total_price %>€</strong></p>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="recieved-bookings">
      <h4>Recieved requests</h4>
      <div class="dash-cards">
        <% @recieved_bookings.each do | recieved_booking | %>
        <div class="dash-card">
          <%= cl_image_tag recieved_booking.costume.photo.key %>
          <div class="dash-card-infos">
            <div>
              <h6><strong><%= recieved_booking.costume.name %></strong></h6>
              <p>Request message: <%= recieved_booking.message %></p>
              <p>Status: <%= recieved_booking.status%></p>
              <p>Total price: <strong><%= recieved_booking.total_price %>€</strong></p>
            </div>
            <div>
              <% if recieved_booking.pending? %>
                <%= link_to "Accept request", booking_path(recieved_booking, { status: "accepted" }), method: :patch, class: "button-accept" %>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CostumeRack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'CostumeRack2.png' %>
    <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div style="min-height: 90vh;"><%= yield %></div>
    <%= render 'shared/footerimage' %>
    <%= render 'shared/footer' %>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="slick/slick.min.js"></script>
    <script type="text/javascript">
    if (document.querySelector('.categorymover')) {
      $(document).ready(function(){
        $('.categorymover').slick({
          // setting-name: setting-value
        });
      });
    }
  </script>
  </body>
</html>

app/views/pages/home.html.erb
<div class = "container">
    <%= image_tag "CostumeRack.png", class: "logopage" %>
    <div class="slogan"><p>Rent costumes or lend someone your costume </p></div>


  <div class = "searchbardiv">
    <%= form_tag costumes_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a costume"
    %>
    <%= submit_tag "Search", class: "btn btn-flat-search" %>
  </div>
  <% end %>
</div>

<%# <div class="home-categories-list d-flex">
  <div class="button-bubble button-bubble--left">
    <button class="button-bubble button-bubble--left">
      <svg width="48" height="48" viewBox="12 12 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d="M21.2 23.4a.998.998 0 0 0 0 1.2l3 4a.999.999 0 1 0 1.6-1.199L23.25 24l2.55-3.402a.997.997 0 0 0-.2-1.399 1 1 0 0 0-1.4.2l-3 4z">
        </path>
      </svg>
    </button>
  </div> %>

  <div>
    <p class = "occasions">
    Occasions
    </p>
    <ul class="categorieslist d-flex">
    <%= link_to costumes_path(occasion: "birthday") do %>
      <li class="clown">
        <div class="list-icon clown">
        </div>
         Birthday
      </li>
    <% end %>
    <%= link_to costumes_path(occasion: "halloween") do %>
      <li class="halloween">
        <div class="list-icon halloween">
        </div>
        <p> Halloween </p>
      </li>
    <% end %>
    <%= link_to costumes_path(occasion: "carnival")  do %>
      <li class="mask">
        <div class="list-icon mask">
        </div>
        <p> Carnival </p>
      </li>
    <% end %>
    <%= link_to costumes_path(occasion: "party")  do %>
      <li class="pirates">
        <div class="list-icon pirates">
        </div>
        <p> Party </p>
      </li>
    <% end %>
    <%= link_to costumes_path(occasion: "christmas")  do %>
      <li class="santa">
        <div class="list-icon santa">
        </div>
        <p> Christmas </p>
      </li>
    <% end %>
    <%= link_to costumes_path(occasion: "animals")  do %>
      <li class="animals">
        <div class="list-icon animals">
        </div>
        <p> Animals </p>
      </li>
    <% end %>
    </ul>
  </div>
</div>

  <%# <div class="categorymover">
    <div>your content</div>
    <div>your content</div>
    <div>your content</div>
  </div> %>

  <%# <div>
    <button class="button-bubble button-bubble--right">
      <svg width="48" height="48" viewBox="12 12 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d="M26.8 24.6a.998.998 0 0 0 0-1.2l-3-4a.999.999 0 1 0-1.6 1.199l2.55 3.4-2.55 3.402a.997.997 0 0 0 .2 1.399 1 1 0 0 0 1.4-.2l3-4z">
        </path>
      </svg>
    </button>
  </div>
</div> %>

<div>
  <p class = "howitworks">
    How it works:
  </p>
    <ul class = "stepslist d-flex">
      <li class="step">
        <%= image_tag "Step1.png" %>
        <p class="steptext text-center">Upload Costumes</p>
      </li>
      <li class="step">
        <%= image_tag "Step2.png" %>
        <p class="steptext text-center">Search for Costumes</p>
      </li>
      <li class="step">
        <%= image_tag "Step3.png" %>
        <p class="steptext text-center"> Easily Book Costumes </p>
      </li>
    </ul>
  </div>
</div>

<div>
  <p class = "persona">
  Costumes for Everyone
  </p>
  <div class= "usertypecards d-flex">
    <%= link_to costumes_path(category: "kids"), class: "card-category", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/7139728/pexels-photo-7139728.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260)" do %>
      Children
    <% end %>

    <%= link_to costumes_path(category: "women"), class: "card-category", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1623967199-cupcake-costume-food-halloween-costume-1623967146.jpg)" do %>
      Women
    <% end %>

    <%= link_to costumes_path(category: "men"), class: "card-category", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://spy.com/wp-content/uploads/2021/07/sfv-1.jpg)" do %>
      Men
    <% end %>

    <%= link_to costumes_path(category: "pets"), class: "card-category", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://img.money.com/2017/10/171018-dog-halloween-costumes.jpg)" do %>
      Pets
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    We <i class="fas fa-heart"></i> your costumes! Rent or rent out costumes with CostumeRack!
  </div>
</div>

app/views/shared/_footerimage.html.erb
<div class="footer-image">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" class="logonavbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("CostumeRack3.png")%>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Upload Costume", new_costume_path, class: "nav-link upload btn btn-flat" %>
        </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://i5.walmartimages.com/asr/768c1077-d262-40bc-872d-cfd3ae86b33f_1.0cac95463c1774eef3e93d818ce3320e.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", class: "avatar dropdown-toggle avatar-square", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Upload Costume", new_user_session_path, class: "nav-link upload btn btn-flat" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>